[package]
name = "ultimate-tic-tac-toe-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.17"
warp = "0.3"
futures-util = "0.3.31"

dotenv = "0.15.0"
dotenv_codegen = "0.15.0"

log = "0.4.22"
env_logger = "0.11.6"